# Update Nomenclature table through Python

Check out [this](https://dev.mysql.com/doc/connector-python/en/connector-python-example-cursor-transaction.html) for tutorial on inserting data into tables.

<span style="color:red">I'd recommend to turn special attention to their example of emp_no retrieval for the auto-incremental value of the last row.
This will be a nice way to directly update the **Old_name** table with the appropriate *nomo_id* foreign key.</span>

Code to obtain information for the Nomenclature table.

The data is new_name of the protein and the occurence of the protein either in bacteria, archaea, or eukarya.
If it is eukaya, whether it is available in mitochondria or chloroplast.

In [7]:
import csv
from collections import Counter
import numpy as np
import itertools 
import mysql.connector
import getpass

uname = input("User name: ")
pw = getpass.getpass("Password: ")
cnx = mysql.connector.connect(user=uname, password=pw, host='130.207.36.75', database='DESIRE')
cursor = cnx.cursor()


''' 
read the csv file and get the elements in each row.
make a list of the occurrences from each cell.
'''
def read_csv (csvfile):
	csvReader = csv.reader(csvfile, delimiter= ',')
	next(csvReader)
	occurList = []
	csvList=[]
	for row in csvReader:
		csvList.append(row)
		rowList = []
		count = 0
		for i in row[1]:
			if i.isalpha() == True:
				rowList.append(i)
		occurList.append(rowList)	
	return occurList,csvList
'''
return the occurList with the lists of occurrences from each cell.
return the csvList with the new names of all the proteins.
'''

def write_csv(occurList, csvList, cursor):
	nomenList=[]
	n=0
	for occurrences in occurList:
		i = 0
		while i < len(occurrences):
			query = ("INSERT INTO `DESIRE`.`Nomenclature`(`new_name`,`occurrence`) VALUES('"+csvList[n][0]+"','"+occurrences[i]+"')")
			cursor.execute(query)
            
			nomenList.append((csvList[n][0], occurrences[i]))
			i+=1
		n+=1
	cnx.commit()
	return 	nomenList

with open("../ban_table1.csv") as csvfile:	
	occurList,csvList = read_csv(csvfile)
	nomenList = write_csv(occurList, csvList, cursor)
	print(nomenList)

cursor.close()
cnx.close()

User name: vchivukula
Password: ········
[('bS1', 'B'), ('bS1', 'm'), ('bS1', 'c'), ('uS2', 'B'), ('uS2', 'A'), ('uS2', 'E'), ('uS2', 'm'), ('uS2', 'c'), ('uS3', 'B'), ('uS3', 'A'), ('uS3', 'E'), ('uS3', 'm'), ('uS3', 'c'), ('uS4', 'B'), ('uS4', 'A'), ('uS4', 'E'), ('uS4', 'c'), ('uS5', 'B'), ('uS5', 'A'), ('uS5', 'E'), ('uS5', 'm'), ('uS5', 'c'), ('bS6', 'B'), ('bS6', 'm'), ('bS6', 'c'), ('uS7', 'B'), ('uS7', 'A'), ('uS7', 'E'), ('uS7', 'm'), ('uS7', 'c'), ('uS8', 'B'), ('uS8', 'A'), ('uS8', 'E'), ('uS8', 'c'), ('uS9', 'B'), ('uS9', 'A'), ('uS9', 'E'), ('uS9', 'm'), ('uS9', 'c'), ('uS10', 'B'), ('uS10', 'A'), ('uS10', 'E'), ('uS10', 'm'), ('uS10', 'c'), ('uS11', 'B'), ('uS11', 'A'), ('uS11', 'E'), ('uS11', 'm'), ('uS11', 'c'), ('uS12', 'B'), ('uS12', 'A'), ('uS12', 'E'), ('uS12', 'm'), ('uS12', 'c'), ('uS13', 'B'), ('uS13', 'A'), ('uS13', 'E'), ('uS13', 'c'), ('uS14', 'B'), ('uS14', 'A'), ('uS14', 'E'), ('uS14', 'm'), ('uS14', 'c'), ('uS15', 'B'), ('uS15', 'A'), ('uS15', 'E'), ('uS15', 'm'), ('uS15', 'c'), ('bS16', 'B'), ('bS16', 'm'), ('bS16', 'c'), ('uS17', 'B'), ('uS17', 'A'), ('uS17', 'E'), ('uS17', 'm'), ('uS17', 'c'), ('bS18', 'B'), ('bS18', 'm'), ('bS18', 'c'), ('uS19', 'B'), ('uS19', 'A'), ('uS19', 'E'), ('uS19', 'c'), ('bS20', 'B'), ('bS20', 'c'), ('bS21', 'B'), ('bS21', 'm'), ('bS21', 'c'), ('bTHX', 'B'), ('bTHX', 'c'), ('eS1', 'A'), ('eS1', 'E'), ('eS4', 'A'), ('eS4', 'E'), ('eS6', 'A'), ('eS6', 'E'), ('eS7', 'E'), ('eS8', 'A'), ('eS8', 'E'), ('eS10', 'E'), ('eS12', 'E'), ('eS17', 'A'), ('eS17', 'E'), ('eS19', 'A'), ('eS19', 'E'), ('eS21', 'E'), ('eS24', 'A'), ('eS24', 'E'), ('eS25', 'A'), ('eS25', 'E'), ('eS26', 'E'), ('eS27', 'A'), ('eS27', 'E'), ('eS28', 'A'), ('eS28', 'E'), ('eS30', 'A'), ('eS30', 'E'), ('eS31', 'A'), ('eS31', 'E'), ('RACK1', 'E')]

This code will help obtain data for both the Nomenclature and Old_name table. Pay attention to the query execution after each query to make sure the query is executed correctly, instead of the one cursor.execute(query1) at the end. Also, I used [this](https://dev.mysql.com/doc/connector-python/en/connector-python-example-cursor-transaction.html) link to get an idea to generate the nom_id using cursor.lastrowid, just the way they generated emp_no = cursor.lastrowid

In [ ]:
import csv
from collections import Counter
import numpy as np
import itertools 
import mysql.connector
import getpass

'''
Generating a Nomenclature table and a Old_name table. The data is new_name of the protein 
and the occurrence of the protein either in bacteria, archaea, or eukarya. 
If it is eukarya, whether it is available in mitochondria or chloroplast.
The table can be directly exported to the database. The write_csv function checks for the occurrence and inputs
the corresponding old name for each of the occurrence. Please pay special attention 
to the code used to upload the output to the database. 
''' 


uname = input("User name: ")
pw = getpass.getpass("Password: ")
cnx = mysql.connector.connect(user=uname, password=pw, host='130.207.36.75', database='DESIRE')
cursor = cnx.cursor()


''' 
read the csv file and get the elements in each row.
make a list of the occurrences from each cell.
'''
def read_csv (csvfile):
	csvReader = csv.reader(csvfile, delimiter= ',')
	next(csvReader)
	occurList = []
	csvList=[]
	for row in csvReader:
		csvList.append(row)
		rowList = []
		count = 0
		for i in row[1]:
			if i.isalpha() == True:
				rowList.append(i)
		occurList.append(rowList)	
	return occurList,csvList
'''
return the occurList with the lists of occurrences from each cell.
return the csvList with the new names of all the proteins.
'''
	
	
def write_csv(occurList, csvList, cursor):
	nomenList=[]
	n=0
	for occurrences in occurList:
		i = 0
		while i < len(occurrences):
			query = ("INSERT INTO `DESIRE`.`Nomenclature`(`new_name`,`occurrence`) VALUES('"+csvList[n][0]+"','"+occurrences[i]+"')")
			cursor.execute(query)
			j = cursor.lastrowid
			nomenList.append((csvList[n][0], occurrences[i]))
			if occurrences[i] == 'B':
				query1 = ("INSERT INTO `DESIRE`.`Old_name`(`nomo_id`,`old_name`, `yeast-human`) VALUES('"+str(j)+"','"+csvList[n][2]+"','"+occurrences[i]+"')")
				cursor.execute(query1)
			elif occurrences[i] == 'A':
				pass
			elif occurrences[i] == 'E':#This won't work (overwrites itself and gets executed further down)
				query1 = ("INSERT INTO `DESIRE`.`Old_name`(`nomo_id`,`old_name`, `yeast-human`) VALUES('"+str(j)+"','"+csvList[n][3]+"','"+'Y'+"')")
				cursor.execute(query1)
				query1 = ("INSERT INTO `DESIRE`.`Old_name`(`nomo_id`,`old_name`, `yeast-human`) VALUES('"+str(j)+"','"+csvList[n][4]+"','"+'H'+"')")
				cursor.execute(query1)
			elif occurrences[i] == 'm':
				query1 = ("INSERT INTO `DESIRE`.`Old_name`(`nomo_id`,`old_name`, `yeast-human`) VALUES('"+str(j)+"','"+csvList[n][5]+"','"+occurrences[i]+"')")
				cursor.execute(query1)
			elif occurrences[i] == 'c':
				query1 = ("INSERT INTO `DESIRE`.`Old_name`(`nomo_id`,`old_name`, `yeast-human`) VALUES('"+str(j)+"','"+csvList[n][6]+"','"+occurrences[i]+"')")
				cursor.execute(query1)
			i+=1
		n+=1
	cnx.commit()
	return 	nomenList


'''
Exporting the required output to the database table
'''


with open("../ban_table_1.csv") as csvfile:	
	occurList,csvList = read_csv(csvfile)
	#write_csv(occurList,csvList)
	nomenList = write_csv(occurList, csvList, cursor)
	#print(nomenList)
	
cursor.close()
cnx.close()

# Nomenclature for merging
Takes in a file with both LSU and SSU proteins, which has 7 columns...

In [5]:
import csv
from collections import Counter
import numpy as np
import itertools 
import mysql.connector
import getpass

'''
Generating a Nomenclature table and a Old_name table. The data is new_name of the protein 
and the occurrence of the protein either in bacteria, archaea, or eukarya. 
If it is eukarya, whether it is available in mitochondria or chloroplast.
The table can be directly exported to the database. The write_csv function checks for the occurrence and inputs
the corresponding old name for each of the occurrence. Please pay special attention 
to the code used to upload the output to the database. 
''' 

uname = input("User name: ")
pw = getpass.getpass("Password: ")
cnx = mysql.connector.connect(user=uname, password=pw, host='130.207.36.75', database='DESIRE')
cursor = cnx.cursor()

def read_csv (csvfile):
	''' 
	Reads csv file with new names, occurences and old names,
	then returns a list of lists for the rows.
	'''
	csvReader = csv.reader(csvfile, delimiter= ',')
	next(csvReader)
	occurList = []
	csvList=[]
	for row in csvReader:
		csvList.append(row)
	return csvList

def execute_old_name_query(row, occurrence, lastrow_id):
	'''
	Checks the current occurence and executes queries for the Old_name table.
	'''
	if occurrence == 'B':
		if row[3]:
			query = ("INSERT INTO `DESIRE`.`Old_name`(`nomo_id`,`old_name`,`N_B_Y_H_A`) VALUES('"+str(lastrow_id)+"','"+row[3]+"','"+occurrence+"')")
			cursor.execute(query)
	elif occurrence == 'A':
		if row[6]:
			query = ("INSERT INTO `DESIRE`.`Old_name`(`nomo_id`,`old_name`,`N_B_Y_H_A`) VALUES('"+str(lastrow_id)+"','"+row[6]+"','"+occurrence+"')")
			cursor.execute(query)
	elif occurrence == 'E':
		if row[4]:
			query = ("INSERT INTO `DESIRE`.`Old_name`(`nomo_id`,`old_name`,`N_B_Y_H_A`) VALUES('"+str(lastrow_id)+"','"+row[4]+"','Y')")
			cursor.execute(query)
		if row[5]:
			query = ("INSERT INTO `DESIRE`.`Old_name`(`nomo_id`,`old_name`,`N_B_Y_H_A`) VALUES('"+str(lastrow_id)+"','"+row[5]+"','H')")
			cursor.execute(query)
	elif occurrence == 'm':
		if row[3]:
			query = ("INSERT INTO `DESIRE`.`Old_name`(`nomo_id`,`old_name`,`N_B_Y_H_A`) VALUES('"+str(lastrow_id)+"','"+row[3]+"','B')")
			cursor.execute(query)
		if row[4]:
			query = ("INSERT INTO `DESIRE`.`Old_name`(`nomo_id`,`old_name`,`N_B_Y_H_A`) VALUES('"+str(lastrow_id)+"','"+row[4]+"','mY')")
			cursor.execute(query)
		if row[5]:
			query = ("INSERT INTO `DESIRE`.`Old_name`(`nomo_id`,`old_name`,`N_B_Y_H_A`) VALUES('"+str(lastrow_id)+"','"+row[5]+"','mH')")
			cursor.execute(query)
	elif occurrence == 'c':
		if row[3]:
			query = ("INSERT INTO `DESIRE`.`Old_name`(`nomo_id`,`old_name`,`N_B_Y_H_A`) VALUES('"+str(lastrow_id)+"','"+row[3]+"','B')")
			cursor.execute(query)
		if row[4]:
			query = ("INSERT INTO `DESIRE`.`Old_name`(`nomo_id`,`old_name`,`N_B_Y_H_A`) VALUES('"+str(lastrow_id)+"','"+row[4]+"','cY')")
			cursor.execute(query)
	else:
		raise ValueError('Occurence can only be B, A, E, m, or c!')
	return True

def upload_csv(csvList, cursor):
	lastrow_id=0
	for row in csvList:
		for occurrence in list(row[2]):
			if row[0][1] == 'S':
				query = ("INSERT INTO `DESIRE`.`Nomenclature`(`new_name`,`occurrence`,`MoleculeGroup`) VALUES('"+row[0]+"','"+ocurrence+"','SSU')")
			elif row[0][1] == 'L':
				query = ("INSERT INTO `DESIRE`.`Nomenclature`(`new_name`,`occurrence`,`MoleculeGroup`) VALUES('"+row[0]+"','"+occurrence+"','LSU')")
			else:
				raise ValueError('Incorrect Molecule group! Can be only L or S: '+row[0])
			cursor.execute(query)
			lastrow_id = cursor.lastrowid
			execute_old_name_query(row, occurrence, lastrow_id)
			query = ("INSERT INTO `DESIRE`.`Old_name`(`nomo_id`,`old_name`,`N_B_Y_H_A`) VALUES('"+str(lastrow_id)+"','"+row[1]+"','BAN')")
			cursor.execute(query)
	cnx.commit()
	return True

with open("../ALL-BAN-NICK.csv") as csvfile:
	csvList = read_csv(csvfile)
	upload_csv(csvList, cursor)
	
cursor.close()
cnx.close()

print("Success!")

User name: ppenev
Password: ········
Success!